name: Format Java

on:
  push:
    branches: [ main ]

jobs:

  formatting:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      statuses: write
    steps:
      - uses: actions/checkout@v3 # v2 minimum required
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"
          github-token: ${{ secrets.GITHUB_TOKEN }}
