name: Run Gradle Build and Test

on: [push]

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Install
        run: ./gradlew install
      
      - name: Setup and execute Gradle 'build' task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Setup and execute Gradle 'test' task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

      - name: Setup and execute Gradle 'testCoverage' task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: testCoverage

      - name: Generate JaCoCo Test Coverage Badge
        if: runner.os == 'Linux'
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: build/reports/jacoco/testCoverage/testCoverage.csv
