name: Run Gradle Build and Test

on: [push]

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Install
        run: ./gradlew install
      
      - name: Setup and execute Gradle 'build' task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Setup and execute Gradle 'test' task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

#       - name: Setup and execute Gradle 'testCoverage' task
#         uses: gradle/gradle-build-action@v2
#         with:
#           arguments: testCoverage

#       - name: Generate JaCoCo Test Coverage Badge
#         if: runner.os == 'Linux'
#         uses: cicirello/jacoco-badge-generator@v2
#         with:
#           badges-directory: badges
#           generate-branches-badge: true
#           generate-summary: true
#           jacoco-csv-file: build/reports/jacoco/testCoverage/testCoverage.csv

#       - name: Log coverage percentages to workflow output
#         if: runner.os == 'Linux'
#         run: |
#           echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
#           echo "branches = ${{ steps.jacoco.outputs.branches }}"
  
#       - name: Upload JaCoCo coverage report as a workflow artifact
#         if: runner.os == 'Linux'
#         uses: actions/upload-artifact@v2
#         with:
#           name: jacoco-report
#           path: badges
  
#       - name: Commit and push the coverage badges and summary file
#         if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request' && runner.os == 'Linux'
#         run: |
#           cd badges
#           if [[ `git status --porcelain *.svg *.json` ]]; then
#             git config --global user.name 'github-actions'
#             git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
#             git add *.svg *.json
#             git commit -m "Autogenerated JaCoCo coverage badges" *.svg *.json
#             git push
#           fi
