name: Run Gradle Build

on: [push, pull_request]

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Install
        run: ./gradlew install
      
      - name: Setup and execute Gradle 'build' task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
